language: ruby
rvm:
- 2.2.0
install:
- travis_retry gem install s3_website -v 2.12.3
- travis_retry npm install
before_script: webpack
script: deploy/s3_deploy.sh
cache:
  bundler: true
  directories:
    - node_modules
env:
  global:
  - secure: kwkoB7QKEbeKMbGgjtKMR58IErob9kCIV3jMXCWjvkykawsW9wbqrzQTmN9za50K4liRMqooUefpfrgGE7L26G00W+f4LF/SMsz1yNRgNFFhABe2J1hc/wykJ4ZfpuR6qsvKBFzU6xFv2SWOxgiTVFej2ipMkUFZVMabgPephbJfdYkvfZRbgqjVs2RXGsO6BDzDfmAku3mZwI/IY0I7jIZ2FKVM44qUOjlhlb9r8/Fuxr0n4hBXZqoNwyCmBJsMFF6xHmcKncHAm2q9VCa9bWXUqx8201/RjZbXqo/MbXBaoIYUVLoEi9zCF9xTEklezXhn4SXjANOFa/rDa9uHpinZXXst9NcjuxtDtZkXiEqAvkHsx8cilMaekjsSswjyj6Xckv0ZEnFQJzRwcPqaw5uoOyhcZELTLAnd3sjrDZE/aIhxil8esDJ6t14i6vw4M/wd3aUQikl4PW9kclTZHt+tKSWSPN+2eZe8aMlv7owkuoann7wAhb4AGZwdRm7Lj7gFNPz7IrhYugNmTai454cO/FKcq5mZh/0CHZ+4elJPCIO6Yf8nQh15u0TVvkX5Rg9ahVzfAUriGe4uy0NIAgbRC8pVbR5SW23dR0bxR5awC7mPu83s67D6JwhqjAkQ7B79e6UE2n3sO+ufOcER6Pp+NMswPsoN3tla31VVpcI=
  - secure: LA4c3gxBNcZKqkTzg+RMVQ8M/7veVt71DjbexJ/TZ3CB5TvfFmPqKomeOavPcQsLIugwA1ncEl8p2dleLCccQcDaW/0ul1xrYO8qiLO4sGfUlf+1DugJiIOa/0dj7ANqdrjXpDF54AEU4B4RDGW1hlarxDjoocCpdDQSyRGTUqYn+E1am7Fn9jILvxyRwkcblIOpriLJ+lHCSThqEbWE4jyxjY/3+Og9rZvcZ5xsTIZZ1SKdhD/8eyJ2Wxs+lWm2UInbtzy6Q0JHsHKU/ujF7AVOhCtOHEaXKlTlrNIk5OFFcr1sYo3C8j5QekA/oFVLTjukY8vcDnvE4nQzHOKth783Xd/ZYC4+W+djmN4fUpuJ+MSVq7nrAXAnbbePcC9Csx9z6cQ76FQPGzODEh2XwlJ7at4xj6uLkfIZeA/cuiRGtPGKHmbmnqYvnWdB6cMK2CsbhsDLBPUe4lypaNWotIkkEVAHtdYZDdr7WJWC/Xp0YpaU5546Fhq2RgSe0xJ7HaS7vkMxyMS9OVcC1ximws1YmNxvYJ4eHidPxln86+b82v+xibP9MNS7BPcXiQZy759PUn9YY4m+/vLLFf03N4OuOs5PrNtlMcD/rvgNIvYel77AM4SJE7+ldBqZjUyJjyoobG7Q3is0kFrVrIXvoqhCO2kdvkisv1BURG/CgDY=
