s3_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
s3_secret: <%= ENV['S3_SECRET_KEY'] %>
s3_bucket: models-resources
s3_key_prefix: leap-motion
s3_endpoint: us-east-1
gzip: true

<% if ENV['TRAVIS_BRANCH'] == 'production' %>
# in this case we are going to deploy this branch to the top level of the domain
# so we need to ignore the version and branch folders
ignore_on_server: ^leap-motion/(version/|branch/)
<% else %>
# in this case we are going to deploy this code to a subfolder of either the branch
# or version folder. So ignore everything except this folder.
ignore_on_server: ^(?!leap-motion/<%= Regexp.escape(ENV['DEPLOY_DIR']) %>/)
<% end %>
max_age:
  "grasp-seasons/*": 600 # 10 minutes
  "grasp-seasons/version/*": 31536000 # 1 year
  "grasp-seasons/branch/*": 60 # 1 minute
